import { COLORS, FONTS, FONT_SIZES } from '../../../shared/constants/tokens.js';

const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bg,
    padding: '16px',
  },
  card: {
    backgroundColor: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    borderRadius: '8px',
    padding: '32px',
    width: '100%',
    maxWidth: '400px',
  },
  title: {
    fontFamily: FONTS.heading,
    fontSize: `${FONT_SIZES[4]}px`,
    color: COLORS.ink,
    marginBottom: '8px',
    textAlign: 'center',
  },
  subtitle: {
    fontFamily: FONTS.body,
    fontSize: `${FONT_SIZES[2]}px`,
    color: COLORS.inkMuted,
    marginBottom: '24px',
    textAlign: 'center',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  label: {
    fontFamily: FONTS.body,
    fontSize: `${FONT_SIZES[1]}px`,
    color: COLORS.ink,
    fontWeight: '500',
  },
  input: {
    fontFamily: FONTS.body,
    fontSize: `${FONT_SIZES[2]}px`,
    padding: '10px 12px',
    border: `1px solid ${COLORS.border}`,
    borderRadius: '6px',
    outline: 'none',
    transition: 'border-color 0.15s',
    backgroundColor: COLORS.surface,
    color: COLORS.ink,
  },
  select: {
    fontFamily: FONTS.body,
    fontSize: `${FONT_SIZES[2]}px`,
    padding: '10px 12px',
    border: `1px solid ${COLORS.border}`,
    borderRadius: '6px',
    outline: 'none',
    backgroundColor: COLORS.surface,
    color: COLORS.ink,
    cursor: 'pointer',
  },
  button: {
    fontFamily: FONTS.body,
    fontSize: `${FONT_SIZES[2]}px`,
    fontWeight: '600',
    padding: '12px',
    border: 'none',
    borderRadius: '6px',
    backgroundColor: COLORS.accent,
    color: '#FFFFFF',
    cursor: 'pointer',
    marginTop: '8px',
    transition: 'opacity 0.15s',
  },
  link: {
    fontFamily: FONTS.body,
    fontSize: `${FONT_SIZES[1]}px`,
    color: COLORS.accent,
    textAlign: 'center',
    marginTop: '16px',
    cursor: 'pointer',
    textDecoration: 'none',
  },
  error: {
    fontFamily: FONTS.body,
    fontSize: `${FONT_SIZES[1]}px`,
    color: COLORS.bug,
    textAlign: 'center',
    marginBottom: '12px',
  },
};

export default styles;
